### PR TITLE
Added GM_config for cached settings

### PR DESCRIPTION
**Pull request by frenchcutgreenbean**
I added support for GM_config adding most of the settings.

Also changed this line 
`const selectedTVTrackers = []; // This was calling TVV even though it was disabled.` 
This was forcing me to use TVV

### CODE REVIEW

**Comment by Audionut** [comment]
I didn't consider that use case, this should work, but untested.

```    
const selectedTVTrackers = ["TVV"]; // Trackers defined here also contain TV movies and the like.

// Add TV trackers if it is a PTP miniseries page, but skip selected TV Trackers handling for now.
if (isMiniSeriesFromSpan) {
    trackers = trackers.concat(tv_trackers.filter(tracker => !selectedTVTrackers.includes(tracker)));
} else {
    tv_trackers.forEach(tracker => {
        if (!selectedTVTrackers.includes(tracker)) {
            excludedTrackers.push({ tracker: tracker, reason: 'Not classified as a Miniseries' });
        }
    });
}

// This also captures TV movies and the like from Collections. Add selected TV Trackers.
if (isMiniSeries) {
    // Filter selectedTVTrackers to only include those that are also in tv_trackers
    const validSelectedTVTrackers = selectedTVTrackers.filter(tracker => tv_trackers.includes(tracker));

    // Only add trackers from validSelectedTVTrackers if they are not already in the trackers array
    validSelectedTVTrackers.forEach(tracker => {
        if (!trackers.includes(tracker)) {
            trackers.push(tracker);
        }
    });
} else {
    selectedTVTrackers.forEach(tracker => {
        if (tv_trackers.includes(tracker)) {
            excludedTrackers.push({ tracker: tracker, reason: 'Not classified as a Miniseries' });
        }
    });
}
```

Thank for the code, I'll need some time to review.

**Comment by Audionut** [comment]
I'm seeing resource not found
`https://cdnjs.cloudflare.com/ajax/libs/gm-config/1.3.3/gm-config.min.js`

And my google-fu is not assisting me to find an alternative.

**Comment by frenchcutgreenbean** [comment]
You're right only this one is needed "https://cdn.jsdelivr.net/gh/sizzlemctwizzle/GM_config@43fd0fe4de1166f343883511e53546e87840aeaf/gm_config.js"

I got that from chatgpt when he also lied to me about creating an onSave function. 🤣 Somehow I didn't even notice it.

**Comment by Audionut** [comment]
I have a love hate relationship with the GTP. Like tonight, trying to get it to make the settings box do what I want.

Thanks again for your code, works great.

**Pull request merged**
