### PR TITLE
Move the AvistaZ sites to API

### PR DESCRIPTION
**Pull request by Audionut**

### CODE REVIEW

**Comment by ehsope** [comment]
After this change I can no longer get the Z sites to work with the [ptp-add-filter-all-releases-anut.js](https://github.com/Audionut/add-trackers/blob/main/ptp-add-filter-all-releases-anut.js) script. They worked perfectly fine before.

**Comment by Audionut** [comment]
Make sure you have the correct credentials added. If it still fails, you can enable debugging in the settings for clues.

**Comment by ehsope** [comment]
The correct credentials are added, It worked once or twice but then broke again. I've enabled debugging but it doesn't seem to do anything.

**Comment by Audionut** [comment]
You'll need to look in your browser console for hints.

https://appuals.com/open-browser-console/

**Pull request merged**
